"""empty message

Revision ID: 3b82da206cb7
Revises: 75fd669a7220
Create Date: 2017-06-16 11:31:47.918648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b82da206cb7'
down_revision = '75fd669a7220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_to_job',
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], )
    )
    op.drop_table('event')
    op.drop_column('skill', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('description', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('recurring', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], [u'job.id'], name=u'event_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'event_pkey')
    )
    op.drop_table('skill_to_job')
    # ### end Alembic commands ###
