"""empty message

Revision ID: 58c5544b2794
Revises: 3b82da206cb7
Create Date: 2017-06-22 16:09:41.716351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c5544b2794'
down_revision = '3b82da206cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vol_to_org',
    sa.Column('volunteer_id', sa.String(length=64), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], )
    )
    op.add_column(u'volunteer', sa.Column('token_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'volunteer', 'token_id')
    op.drop_table('vol_to_org')
    # ### end Alembic commands ###
