"""empty message

Revision ID: 75fd669a7220
Revises: caf41d99427d
Create Date: 2017-06-14 08:30:36.532295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fd669a7220'
down_revision = 'caf41d99427d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'organization', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column(u'skill', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'skill', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column(u'organization', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_table('event')
    # ### end Alembic commands ###
